# Generated by Django 3.2.13 on 2022-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Username', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Message', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
